apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-k8s-flotsam-postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: scw-bssd
