apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-k8s-flotsam-jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: scw-bssd
