# Here is an example about how you can have the secrets required to run the scaleway-csi driver.
# To generate an access/secret, see https://www.scaleway.com/en/docs/generate-an-api-token/
---
apiVersion: v1
kind: Secret
metadata:
  name: scaleway-secret
  namespace: kube-system
type: Opaque
stringData:
  SCW_ACCESS_KEY: "SCW4CMTQPZ9BQNRPXNCB"
  SCW_SECRET_KEY: "76cf7aed-df13-47c9-b724-021d2b19af70"
  # Project ID could also be an Organization ID
  SCW_DEFAULT_PROJECT_ID: "75d227ef-11fc-40df-bbf9-ad50763be380"
  # The default zone where the block volumes will be created, ex: fr-par-1
  SCW_DEFAULT_ZONE: "fr-par-1"
