name: GitHub Actions Demo
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: node:18.9.0-alpine3.15
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: '0'
      - name: Install dependencies
        run: npm ci
      - uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint,test,build
          all: 'true'
